apply plugin: 'com.android.library'
apply plugin: 'maven-publish'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'

publishing {
    publications {
        release(MavenPublication) {
            groupId = 'kore.botsdk'
            artifactId = 'korebotsdklib'
            version = '11.0.2'
        }
    }
}

android {
    compileSdk 36

    publishing {
        singleVariant('release') {
            withSourcesJar()
        }
    }

    buildFeatures {
        buildConfig true
        dataBinding true
    }

    defaultConfig {
        minSdkVersion 26
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    dependencies {
        api 'androidx.appcompat:appcompat:1.7.1'
        api 'de.greenrobot:eventbus:2.4.1'

        api 'com.squareup.retrofit2:retrofit:3.0.0'
        api 'com.squareup.okhttp3:logging-interceptor:5.4.0'
        api 'com.google.code.gson:gson:2.14.0'
        api "com.squareup.okhttp3:okhttp:5.4.0"
        api 'com.squareup.retrofit2:converter-gson:3.0.0'
        api 'io.reactivex.rxjava2:rxandroid:2.1.1'
        api 'com.jakewharton.retrofit:retrofit2-rxjava2-adapter:1.0.0'
        api "org.apache.commons:commons-lang3:3.20.0"
    }
    namespace 'kore.korebotsdklib'
    lint {
        targetSdk 36
    }
    testOptions {
        targetSdk 36
    }
}
